extern const GeoLayout pokey_000_switch_opt1[];
extern const GeoLayout pokey_head_geo[];
extern Lights1 pokey_base_lights;
extern Lights1 pokey_spines_lights;
extern Lights1 pokey_face_lights;
extern Lights1 pokey_blink_lights;
extern u8 pokey_face_rgba16[];
extern u8 pokey_blink_rgba16[];
extern Vtx pokey_000_displaylist_mesh_layer_1_vtx_0[94];
extern Gfx pokey_000_displaylist_mesh_layer_1_tri_0[];
extern Vtx pokey_000_displaylist_mesh_layer_1_vtx_1[49];
extern Gfx pokey_000_displaylist_mesh_layer_1_tri_1[];
extern Vtx pokey_000_displaylist_mesh_layer_4_vtx_0[4];
extern Gfx pokey_000_displaylist_mesh_layer_4_tri_0[];
extern Gfx mat_pokey_base[];
extern Gfx mat_pokey_spines[];
extern Gfx mat_pokey_face[];
extern Gfx mat_revert_pokey_face[];
extern Gfx mat_pokey_blink[];
extern Gfx mat_revert_pokey_blink[];
extern Gfx pokey_000_displaylist_mesh_layer_1[];
extern Gfx pokey_000_displaylist_mesh_layer_1_mat_override_blink_0[];
extern Gfx pokey_000_displaylist_mesh_layer_4[];
extern Gfx pokey_000_displaylist_mesh_layer_4_mat_override_blink_0[];
extern Gfx pokey_material_revert_render_settings[];

extern const GeoLayout pokey_body_part_geo[];
extern Lights1 pokey_body_lights;
extern Lights1 pokey_spines_lights;
